# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: /root/visualise-3d
    docker:
      - image: unityci/editor:ubuntu-2020.3.33f1-linux-il2cpp-1
    environment:
      UNITY: /usr/bin/unity-editor
      TOP: /root/visualise-3d
      INFO: /root/visualise-3d/build_info
    steps:
      - checkout
      - run:
          name: Show Info
          command: |
            lsb_release -a
            whoami;groups

