# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: /root/visualise-3d
    docker:
      - image: unityci/editor:ubuntu-2020.3.33f1-linux-il2cpp-1
    environment:
      UNITY: /usr/bin/unity-editor
      TOP: /root/visualise-3d
      BUILD: /root/visualise-3d/build
    steps:
      - checkout
      - run:
          name: Show Info
          command: |
            lsb_release -a
            whoami;groups
            echo "$UNITY_LICENSE_CONTENT"
      - run:
          name: Preparation
          command: |
            test -x $UNITY
            mkdir -p $BUILD
            mkdir -p ~/.cache/unity3d
            mkdir -p ~/.local/share/unity3d/Unity/
            echo "$UNITY_LICENSE_CONTENT" | base64 --decode | tr -d '\r' > ~/.local/share/unity3d/Unity/Unity_lic.ulf
      - run:
          name: Run Build
          command: |
            export __targetDir=$BUILD
            export __targetFile=visualise-3d
            $UNITY -batchmode -quit -projectPath $TOP -testResults $BUILD/results.xml -logFile $BUILD/logs.txt -executeMethod MacOS.Build
      - store_artifacts:
          path: /root/visualise-3d/build
          destination: ./build